feat: Added CD

diff --git a/.github/workflows/post_merged_to_main.yml b/.github/workflows/post_merged_to_main.yml
--- a/.github/workflows/post_merged_to_main.yml
+++ b/.github/workflows/post_merged_to_main.yml
@@ -4,14 +4,20 @@ run-name: Post merged to main by ${{ github.actor }}
 on:
   workflow_call:
     inputs:
-    
+
       image_to_use:
         required: true
         type: string
+      
+      artifact_rid:
+        required: true
+        type: string
+
     secrets:
       PAT:
         required: false
-      
+      NIDAP_TOKEN:
+        required: false      
 jobs:
   Adding_documentation_files_and_publish_page:
     runs-on: ubuntu-latest
@@ -96,6 +102,7 @@ jobs:
 
           echo "Start updating versions"
           automatic_versioning="$(semantic-release version --no-push --no-commit)"
+          echo "VERSION=$automatic_versioning" >> $GITHUB_ENV
           echo "New Version: $automatic_versioning"
           sed -i "s/version='[0-9.]*'/version='$automatic_versioning'/" setup.py
 
@@ -115,7 +122,49 @@ jobs:
           git push -f origin main
           # fi
 
-          # Calling documentation de script
+          echo "$(git log --oneline --ancestry-path ${{github.event.pull_request.head.sha}}..HEAD)" > \
+              $current_wd/commit_history_log.log
+
+          commit_log_location="$current_wd/commit_history_log.log"
+
+          cp $(pwd)/Conda_Recipe/meta.yaml $current_wd
+
+          conda_recipe="$current_wd/meta.yaml"
+          change_log_location="$current_wd/commit_history_log.log"
+
+          echo "conda_recipe=$conda_recipe" >> $GITHUB_ENV
+          echo "commit_log_location=$commit_log_location" >> $GITHUB_ENV
+          
+          echo "Create release tag for Continueous Deployment"
+
+          latest_commit_hash=$(git rev-parse HEAD)
+          TAG_NAME="continuous_deployment"
+
+          # Check if the tag exists locally
+          if git rev-parse -q --verify "refs/tags/$TAG_NAME" >/dev/null; then
+              echo "Local tag '$TAG_NAME' exists. Deleting..."
+              git tag -d "$TAG_NAME"
+          else
+              echo "Local tag '$TAG_NAME' does not exist."
+          fi
+
+          # Check if the tag exists remotely
+          if git ls-remote --tags origin | grep -q "refs/tags/$TAG_NAME"; then
+              echo "Remote tag '$TAG_NAME' exists. Deleting..."
+              git push origin ":refs/tags/$TAG_NAME"
+          else
+              echo "Remote tag '$TAG_NAME' does not exist."
+          fi
+
+          git tag \
+            -a "$TAG_NAME" \
+            -m "Automatically tagged latest commit for continuous_deployment." \
+            $latest_commit_hash
+
+          git push origin $TAG_NAME
+
+          # Generating GitHub page now
+          # Calling documentation script
           bash ../gitflow-py/src/document_generation.sh
 
           rm commit_log.log
@@ -164,4 +213,158 @@ jobs:
           fi
           
           echo "Process completed."
+
+      - name: Generating Conda Package
+        id: prepare-conda-pkg 
+        if: ${{ success() }}
+        run: |
+
+          export current_wd="/__w/${GITHUB_REPOSITORY#*/}/${GITHUB_REPOSITORY#*/}"
+          cd $current_wd/${GITHUB_REPOSITORY#*/}
+
+          git checkout main
+
+          cd ../
+          mkdir conda_pkg_building
+          cd conda_pkg_building
+
+          CONDA_DIR=$(pwd)
+          BRANCH_NAME="Conda_Package"
+          
+          export MY_GIT_TOKEN=${{ secrets.GITHUB_TOKEN }}
+          export MY_GIT_USERNAME=${{ github.actor }}
+          export MY_GIT_EMAIL=${{ github.event.pusher.email }}
+          
+          git config --global user.name "$MY_GIT_USERNAME"
+          git config --global user.email "$MY_GIT_EMAIL"
+          git config --global url."https://api:$MY_GIT_TOKEN@github.com/".insteadOf "https://github.com/"
+          git config --global url."https://ssh:$MY_GIT_TOKEN@github.com/".insteadOf "ssh://git@github.com/"
+          git config --global url."https://git:$MY_GIT_TOKEN@github.com/".insteadOf "git@github.com:"
+          
+          git config --global --add safe.directory "$current_wd"
+
+          # Check if conda-build is installed
+          if ! command -v conda-build &> /dev/null; then
+              echo "conda-build is not installed. Installing..."
+              conda install -c conda-forge conda-build
+          fi
+
+          echo "#####################################################"
+          conda config --add channels conda-forge
+          conda config --append channels bioconda
+          conda config --get channels
+          conda clean --all
+
+          echo "#####################################################"
+
+          REPO_NAME_LOWERCASE=$(echo ${GITHUB_REPOSITORY#*/} | \
+                      tr '[:upper:]' '[:lower:]')
+
+          PACKAGE_NAME="$REPO_NAME_LOWERCASE"
+          
+          cp -rf ${{ env.conda_recipe }} $PACKAGE_NAME
+
+          sed -i "s/<CURRENT_VERSION>/$VERSION/g" $PACKAGE_NAME/meta.yaml
+
+          echo "\n\n##########Current Recipe:##################\n\n" 
+
+          cat $PACKAGE_NAME/meta.yaml
+
+          echo "\n\n##########################################\n\n"       
+          
+          # Construct the package name as "r-repository_name"
+
+          RECIPE_DIR="$(pwd)/$PACKAGE_NAME"
+
+          echo "Recipe is now in $RECIPE_DIR."
+
+          echo "#####################################################"
+
+          # Construct the package name as "r-repository_name"
+          RECIP_DIR="GITHUB_REPOSITORY"
+
+          # Build the Conda package while ignoring tests
+          echo "Building Conda Package Now."
+          conda mambabuild --no-test --python=3.8.16 $PACKAGE_NAME/
+
+          PKG_PATH=$(find "/root/miniconda3/conda-bld" -name '*.tar.bz2')
+          # --build-only \
+          echo "Package build in $PKG_PATH"
+          
+          echo "#####################################################"
+          echo "Package Built! Uploading to $BRANCH_NAME now"         
+
+          cd $current_wd/${GITHUB_REPOSITORY#*/}
+
+          BRANCH_NAME="Conda_Package"
+
+          git checkout "$BRANCH_NAME"
+
+          # Move the built package to the current directory
+          echo "Moving Conda Package Now."
+
+          PKG_NAME=$(basename "$PKG_PATH")
+          DEST_NAME="$PKG_NAME"
+
+          mv $PKG_PATH .
+
+          git add *.tar.bz2
+
+          current_pkg="$(basename "$PKG_PATH")"
+          
+          echo "current_pkg="$current_pkg"" >> $GITHUB_ENV
+          echo "###############################################################"
+          echo "\nCurrent package: $current_pkg"
+
+      - name: Continuous Deployment to NIDAP
+        id: nidap-cd
+        if: ${{ success() }}
+        run: |
+          export current_wd="/__w/${GITHUB_REPOSITORY#*/}/${GITHUB_REPOSITORY#*/}"
+          cd $current_wd
+          cd ${GITHUB_REPOSITORY#*/}
+
+          conda install curl
+          
+          echo "Package to Upload: ${{ env.current_pkg }}"
+
+          TOKEN="${{ secrets.NIDAP_TOKEN }}"
+          PACKAGE="${{ env.current_pkg }}"
+          PLATFORM="linux-64" # replace with the package platform (e.g. noarch, linux-64, osx-64)
+          response=$(curl \
+                    -H "Authorization: Bearer $TOKEN" \
+                    -H "Content-Type: application/octet-stream" \
+                    --data-binary "@$PACKAGE" \
+                    -XPUT "https://nidap.nih.gov/artifacts/api/repositories/${{ inputs.artifact_rid }}/contents/release/conda/$PLATFORM/$PACKAGE" \
+                    2>&1)
+          current_datetime="$(date +"%Y-%m-%d %H:%M:%S")"
+          echo "\nDatetime: $current_datetime, Version:  ${{ env.current_pkg }}"
+          echo "\nDatetime: $current_datetime, Version:  ${{ env.current_pkg }}" >> README.md
+
+          current_log_name=${{ env.current_pkg }}
+          current_log_name="${current_log_name%.tar.bz2}"
+          current_log_name="Commit_Log_$current_log_name.log"
+
+          mv "${{ env.commit_log_location }}" "$current_log_name"
+
+          git add ./$current_log_name
+
+          echo "<br>[View Commit Log]($current_log_name)" >> README.md
+
+          echo "#########################################################"
+
+          # Check if the response contains an error message
+          if echo "$response" | grep -q "errorCode"; then
+            error_name=$(echo "$response" | grep -o '"errorName":"[^"]*' | awk -F'"' '{print $4}')
+            echo "Error message: $error_name"
+            echo "<br>Deployment Status: $error_name" >> README.md
+          else
+            echo "Update Success!"
+            echo "Package ${{ env.current_pkg }} is now on NIDAP."
+            echo "<br>Deployment Status: Success" >> README.md
+          fi
+
+          git commit -a -m "Automatically build conda package"
+
+          git push -f origin $BRANCH_NAME
     
